version: '1.0'
services:
 postgres-db:
   container_name: postgres-db-admin
   image: 'postgres:latest'
   ports:
     - '5432:5432'
   environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

 app:
   build: .
   ports:
     - '3000:3000'
   environment:
     DATABASE_URL: ${DATABASE_URL}